# Application name
spring.application.name=FlightBookingSystem

# Logging
logging.level.root=INFO
logging.level.com.flight=DEBUG
logging.level.org.springframework.boot=WARN


spring.data.mongodb.uri=mongodb://localhost:27017/FlightBookingSystemWebFlux
